Controllers/SkillController.cs
using BusinnessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Portfolio.Controllers
{
    public class SkillController : Controller
    {
        SkillManager skillManager = new SkillManager(new EFSkillDAL());
        public IActionResult Index()
        {
            ViewBag.d1 = "Yetenekler";
            ViewBag.d2 = "Yetenekler";
            var values = skillManager.TGetList();
            return View(values);
        }


        [HttpGet]
        public IActionResult AddSkill()
        {
            ViewBag.d1 = "Yetenek Ekleme";
            ViewBag.d2 = "Yetenekler";
            return View();
        }


        [HttpPost]
        public IActionResult AddSkill(Skill s)
        {
            skillManager.TAdd(s);
            return RedirectToAction("Index");
        }


        public IActionResult DeleteSkill(int id)
        {
            var values = skillManager.GetById(id);
            skillManager.TDelete(values);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult EditSkill(int id)
        {
            var values = skillManager.GetById(id);
            return View(values);
        }

        [HttpPost]
        public IActionResult EditSkill(Skill s)
        {
            skillManager.TUpdate(s);
            return RedirectToAction("Index");
        }
    }
}

Views/Skill/AddSkill.cshtml
@{
    ViewData["Title"] = "AddSkill";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}




<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Yetenek Ekle</h4>
            <p class="card-description">
                Yeni Yetenek Ekle
            </p>
            <form class="forms-sample" method="post">
                <div class="form-group row">
                    <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Yetenek Adı</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="exampleInputUsername2" name="Title" placeholder="Yetenek Adı">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Değer</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="exampleInputUsername2" name="Value" placeholder="Değer">
                    </div>
                </div>
                <button class="btn btn-primary mr-2">Kaydet</button>
            </form>
        </div>
    </div>
</div>

Views/Skill/EditSkill.cshtml
@model EntityLayer.Concrete.Skill
@{
    ViewData["Title"] = "EditSkill";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Yetenek Ekle</h4>
            <p class="card-description">
                Yeni Yetenek Ekle
            </p>
            @using (Html.BeginForm("EditSkill", "Skill", FormMethod.Post, new { @class = "form-sample" }))
            {
                @Html.HiddenFor(x=>x.Id)
                <div class="form-group row">
                    <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Yetenek Adı</label>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(x => x.Title, new {@class="form-control"})
                    </div>
                </div>
                <div class="form-group row">
                    <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Değer</label>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(x => x.Value, new { @class = "form-control" })
                    </div>
                </div>
                <button class="btn btn-primary mr-2">Kaydet</button>

            }
        </div>
    </div>
</div>

Views/Skill/Index.cshtml
@using EntityLayer.Concrete
@model List<Skill>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Striped Table</h4>
            <p class="card-description">
                <a href="Skill/AddSkill" class="btn btn-success">Yeni Yetenek Ekle</a>
            </p>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th> ID </th>
                            <th> Yetenek </th>
                            <th> Değer </th>
                            <th> İşlemler </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td class="py-1">
                                @item.Id
                            </td>
                            <td> @item.Title</td>
                            <td>
                                <div class="progress">
                                    <div class="progress-bar bg-success" role="progressbar" style="width: @item.Value%" aria-valuenow="@item.Value" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </td>
                            <td>
                                <a href="/Skill/EditSkill/@item.Id" class="btn btn-info">Güncelle</a> || <a href="/Skill/DeleteSkill/@item.Id" class="btn btn-danger">Sil</a>
                            </td>
                        </tr>
                        }

                      
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>